version: '2.3'
networks:
  infra_default:
    external: true
services:
  local-redis:
    image: 'redis:4.0.1-alpine'
    restart: 'unless-stopped'
    mem_limit: '1G'
    command: 'redis-server --requirepass ${REDIS_PASSWORD}'
    volumes:
      - '${ROOT_FOLDER}/redis/data:/data'
  kue:
    image: 'valentinvieriu/booksclub:kue-1.0.1'
    restart: 'unless-stopped'
    mem_limit: '512M'
    depends_on:
      - local-redis
    networks:
      - default
      - infra_default
    environment:
      NODE_ENV: 'production'
      REDIS_URL: '${REDIS_URL}'

  chrome-headless:
    image: 'valentinvieriu/chrome-headless:64.0.3282.167-1'
    restart: 'unless-stopped'
    shm_size: '1G'
    restart: 'always'
    mem_limit: '1G'
    cap_add: 
      - 'SYS_ADMIN'
    command: '--ignore-certificate-errors --no-sandbox --headless --disable-gpu --hide-scrollbars -incognito --window-size=1280,1280 --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222'
    volumes: 
      - '${ROOT_FOLDER}/chromedata:/data'
    # environment: 
    #   VIRTUAL_HOST: 'ws://chrome-headless.${TLD}'

  node-screenshots:
    image: 'valentinvieriu/node-screenshots:1.0.4'
    restart: 'unless-stopped'
    depends_on:
      - local-redis
      - chrome-headless
    mem_limit: '1G'
    environment:
      FILES_CLEAN_TIMEOUT: '10'
      WATCH_QUEUE: '1'
      NODE_ENV: 'production'
      REDIS_URL: '${REDIS_URL}'
      REMOTE_HOST: 'chrome-headless'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/healthcheck']
      interval: 1m
      timeout: 10s
      retries: 3
    volumes: 
      - '${ROOT_FOLDER}/screenshots:/app/screenshots'

  hnews:
    container_name: hnews
    image: valentinvieriu/hnews:1.0.4
    build: .
    restart: 'unless-stopped'
    mem_limit: '1G'
    # memswap_limit: 0
    command: 'node server.js'
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      REDIS_URL: ${REDIS_URL}
      THUMB_BASE_URL: ${THUMB_BASE_URL}
      MICRO_CACHE: 'true'
    labels:
        - "traefik.frontend.rule=Host:${DOMAIN}.${TLD},hnews.beer42.de"
        - "traefik.port=${PORT}"
    ports:
      - '80:${PORT}'
    # volumes: 
    #   - ./fetchImages.js:/usr/src/app/fetchImages.js
    #   - ./server.js:/usr/src/app/server.js